server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/review_genie?characterEncoding=UTF-8&useUnicode=true
    username: kt
    password: kt123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 실행 시 엔티티에 맞춰 테이블 생성
    show-sql: true
    properties:
      hibernate:
        connection:
          characterEncoding: UTF-8
          useUnicode: true
        jdbc:
          time_zone: UTC
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  charset:
    console: UTF-8
    file: UTF-8
  flyway:
    enabled: false # 초기 데이터 삽입을 위해 일시적으로 비활성화
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

external-api:
  review-url: "http://localhost:8080/api/reviews"

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
