server:
  port: 8080

spring:
  application:
    name: review-genie
  datasource:
    url: jdbc:postgresql://localhost:5432/review_genie
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

external-api:
  review-url: "http://localhost:8080/api/reviews"