server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/review_genie
    username: kt
    password: kt123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 엔티티에 맞춰 테이블 변경
    show-sql: true

external-api:
  review-url: "http://localhost:8080/api/reviews"
